server.port = ${SERVER_PORT:8080}

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


keycloak.realm = demo
keycloak.auth-server-url = http://${KEYCLOAK_SERVER_URL:localhost}:8080/auth
keycloak.ssl-required = external
keycloak.resource = spring-backend
keycloak.use-resource-role-mappings = true
keycloak.bearer-only = true
# Usamos keycloak y spring security definida en SecurityConfig
keycloak.principal-attribute=preferred_username
#Overrride problem with bean duplication in keycloak and spring security
spring.main.allow-bean-definition-overriding=true